const products = [
  
  {
    name: "Classic Denim Jacket",
    description: "A timeless, straight-cut denim jacket made from high-quality organic cotton. Perfect for layering.",
    brand: "EcoWear",
    category: "fashion",
    price: 4999,
    discountPrice: 4499,
    currency: "INR",
    isOnSale: true,
    sku: "FAS-DJ-001",
    stock: 150,
    availabilityStatus: "In Stock",
    images: ["/images/denim-jacket-front.jpg", "/images/denim-jacket-back.jpg"],
    thumbnail: "/images/denim-jacket-thumb.jpg",
    variants: [
      { name: "Color", value: "Blue" },
      { name: "Size", value: "S, M, L, XL" },
    ],
    specifications: [
      { key: "Material", value: "100% Organic Cotton" },
      { key: "Fit", value: "Regular" },
    ],
    shippingDetails: { weight: 1.2, dimensions: { length: 30, width: 25, height: 5 } },
    tags: ["denim", "jacket", "outerwear", "sale"],
  },
  {
    name: "Summer Floral Maxi Dress",
    description: "Lightweight rayon maxi dress with a vibrant floral print and adjustable straps. Ideal for warm weather.",
    brand: "Bloom",
    category: "fashion",
    price: 3499,
    sku: "FAS-MD-002",
    stock: 75,
    availabilityStatus: "In Stock",
    images: ["/images/floral-dress-1.jpg"],
    thumbnail: "/images/floral-dress-thumb.jpg",
    variants: [{ name: "Size", value: "XS, S, M, L" }],
    specifications: [{ key: "Fabric", value: "Rayon" }],
    tags: ["dress", "maxi", "floral", "women"],
  },
  {
    name: "Men's Slim Fit Chinos",
    description: "Comfortable and stylish slim-fit cotton chinos in a versatile olive green.",
    brand: "StyleCo",
    category: "fashion",
    price: 2800,
    sku: "FAS-CH-003",
    stock: 90,
    availabilityStatus: "In Stock",
    images: ["/images/chinos-olive.jpg"],
    thumbnail: "/images/chinos-thumb.jpg",
    variants: [
      { name: "Color", value: "Olive" },
      { name: "Waist Size", value: "30, 32, 34, 36, 38" },
    ],
    tags: ["men", "trousers", "chinos"],
  },
  {
    name: "Leather Crossbody Bag",
    description: "Small, genuine leather crossbody bag with multiple compartments and an adjustable strap.",
    brand: "LuxLeather",
    category: "fashion",
    price: 7500,
    discountPrice: 6000,
    isOnSale: true,
    sku: "FAS-CB-004",
    stock: 30,
    availabilityStatus: "Limited",
    images: ["/images/crossbody-brown.jpg"],
    thumbnail: "/images/crossbody-thumb.jpg",
    tags: ["bag", "accessory", "leather"],
  },

  // 📚 BOOKS (3 Products)
  {
    name: "The Alchemist",
    description: "A philosophical novel by Paulo Coelho. It's a story about a young shepherd who travels to the Egyptian desert.",
    brand: "HarperCollins",
    category: "books",
    price: 399,
    sku: "BOK-NOVEL-005",
    stock: 200,
    availabilityStatus: "In Stock",
    images: ["/images/alchemist-cover.jpg"],
    thumbnail: "/images/alchemist-thumb.jpg",
    specifications: [
      { key: "Format", value: "Paperback" },
      { key: "ISBN", value: "978-0062315007" },
      { key: "Pages", value: "208" },
    ],
    tags: ["fiction", "philosophy", "classic"],
  },
  {
    name: "Introduction to JavaScript Programming",
    description: "A comprehensive guide for beginners to learn modern JavaScript development from scratch.",
    brand: "TechPress",
    category: "books",
    price: 1200,
    discountPrice: 1050,
    isOnSale: true,
    sku: "BOK-TECH-006",
    stock: 50,
    availabilityStatus: "In Stock",
    images: ["/images/js-book.jpg"],
    thumbnail: "/images/js-book-thumb.jpg",
    specifications: [
      { key: "Format", value: "Hardcover" },
      { key: "Language", value: "English" },
    ],
    tags: ["technology", "programming", "education"],
  },
  {
    name: "The Great Gatsby",
    description: "F. Scott Fitzgerald's classic novel of the Jazz Age, exploring themes of decadence, idealism, and social upheaval.",
    brand: "Scribner",
    category: "books",
    price: 250,
    sku: "BOK-LIT-007",
    stock: 0,
    availabilityStatus: "Out of Stock",
    images: ["/images/gatsby-cover.jpg"],
    thumbnail: "/images/gatsby-thumb.jpg",
    tags: ["literature", "classic", "english"],
  },

  // 🎶 INSTRUMENT (3 Products)
  {
    name: "Acoustic Dreadnought Guitar",
    description: "Full-size acoustic guitar with a dreadnought body for a rich, loud sound. Perfect for beginners and intermediates.",
    brand: "StringMaster",
    category: "instrument",
    price: 8999,
    sku: "INS-GT-008",
    stock: 15,
    availabilityStatus: "Limited",
    images: ["/images/acoustic-guitar.jpg"],
    thumbnail: "/images/acoustic-guitar-thumb.jpg",
    specifications: [
      { key: "Top Wood", value: "Spruce" },
      { key: "Back/Sides", value: "Mahogany" },
      { key: "Size", value: "41 inch" },
    ],
    tags: ["guitar", "string", "music", "acoustic"],
  },
  {
    name: "Digital Electronic Keyboard (61-Key)",
    description: "61-key portable electronic keyboard with 300 voices and a lesson function for learning.",
    brand: "TonePro",
    category: "instrument",
    price: 6500,
    discountPrice: 5850,
    isOnSale: true,
    sku: "INS-KB-009",
    stock: 25,
    availabilityStatus: "In Stock",
    images: ["/images/keyboard.jpg"],
    thumbnail: "/images/keyboard-thumb.jpg",
    specifications: [
      { key: "Keys", value: "61" },
      { key: "Polyphony", value: "32-note" },
    ],
    tags: ["keyboard", "piano", "electronic"],
  },
  {
    name: "Harmonica - Diatonic (Key of C)",
    description: "Standard 10-hole diatonic harmonica, key of C. Excellent quality for blues and folk music.",
    brand: "ReedCraft",
    category: "instrument",
    price: 950,
    sku: "INS-HM-010",
    stock: 60,
    availabilityStatus: "In Stock",
    images: ["/images/harmonica.jpg"],
    thumbnail: "/images/harmonica-thumb.jpg",
    specifications: [{ key: "Key", value: "C" }],
    tags: ["wind", "blues", "mouth organ"],
  },

  // 📱 GADGETS (4 Products)
  {
    name: "Wireless Noise-Cancelling Headphones",
    description: "Over-ear headphones with superior noise cancellation and up to 30 hours of playback.",
    brand: "AudioPro",
    category: "gadgets",
    price: 12999,
    sku: "GAD-HP-011",
    stock: 45,
    availabilityStatus: "In Stock",
    images: ["/images/headphones-black.jpg"],
    thumbnail: "/images/headphones-thumb.jpg",
    variants: [{ name: "Color", value: "Black, Silver" }],
    specifications: [
      { key: "Connectivity", value: "Bluetooth 5.0" },
      { key: "Battery Life", value: "30 Hours" },
    ],
    tags: ["audio", "wireless", "ANC", "electronics"],
  },
  {
    name: "Portable Power Bank (10000mAh)",
    description: "Compact power bank with fast charging support for smartphones and tablets.",
    brand: "ChargeFast",
    category: "gadgets",
    price: 1499,
    discountPrice: 1299,
    isOnSale: true,
    sku: "GAD-PB-012",
    stock: 300,
    availabilityStatus: "In Stock",
    images: ["/images/powerbank.jpg"],
    thumbnail: "/images/powerbank-thumb.jpg",
    specifications: [
      { key: "Capacity", value: "10000mAh" },
      { key: "Ports", value: "USB-A, USB-C" },
    ],
    tags: ["charger", "mobile", "accessory"],
  },
  {
    name: "Smart Fitness Watch",
    description: "Waterproof smart watch with heart rate monitoring, sleep tracking, and multiple sport modes.",
    brand: "HealthTech",
    category: "gadgets",
    price: 5500,
    sku: "GAD-SW-013",
    stock: 70,
    availabilityStatus: "In Stock",
    images: ["/images/smartwatch.jpg"],
    thumbnail: "/images/smartwatch-thumb.jpg",
    variants: [{ name: "Strap Color", value: "Black, Red, Blue" }],
    specifications: [{ key: "Water Resistance", value: "5 ATM" }],
    tags: ["wearable", "fitness", "watch"],
  },
  {
    name: "Mini Drone with HD Camera",
    description: "Beginner-friendly mini drone with a 720p camera and altitude hold function.",
    brand: "SkyFly",
    category: "gadgets",
    price: 4800,
    sku: "GAD-DR-014",
    stock: 12,
    availabilityStatus: "Limited",
    images: ["/images/mini-drone.jpg"],
    thumbnail: "/images/mini-drone-thumb.jpg",
    shippingDetails: { weight: 0.5, dimensions: { length: 20, width: 15, height: 8 } },
    tags: ["drone", "toys", "camera"],
  },

  // 💎 JEWELERY (3 Products)
  {
    name: "Sterling Silver Stud Earrings",
    description: "Classic 5mm round cubic zirconia stud earrings set in 925 sterling silver.",
    brand: "SparkleJewels",
    category: "jewelery",
    price: 1899,
    discountPrice: 1500,
    isOnSale: true,
    sku: "JWL-ER-015",
    stock: 110,
    availabilityStatus: "In Stock",
    images: ["/images/silver-studs.jpg"],
    thumbnail: "/images/silver-studs-thumb.jpg",
    specifications: [
      { key: "Metal", value: "925 Sterling Silver" },
      { key: "Stone", value: "Cubic Zirconia" },
    ],
    tags: ["earrings", "silver", "women"],
  },
  {
    name: "Men's Stainless Steel Chain Necklace",
    description: "Durable and anti-tarnish stainless steel curb chain necklace, 24 inches long.",
    brand: "ForgeMetals",
    category: "jewelery",
    price: 999,
    sku: "JWL-NK-016",
    stock: 80,
    availabilityStatus: "In Stock",
    images: ["/images/steel-chain.jpg"],
    thumbnail: "/images/steel-chain-thumb.jpg",
    specifications: [{ key: "Material", value: "Stainless Steel" }],
    tags: ["necklace", "men", "chain"],
  },
  {
    name: "Handcrafted Gemstone Ring",
    description: "Unique, adjustable ring featuring a natural amethyst stone, set in a brass base.",
    brand: "ArtisanCraft",
    category: "jewelery",
    price: 3200,
    sku: "JWL-RG-017",
    stock: 20,
    availabilityStatus: "Limited",
    images: ["/images/gemstone-ring.jpg"],
    thumbnail: "/images/gemstone-ring-thumb.jpg",
    variants: [{ name: "Stone", value: "Amethyst" }],
    tags: ["ring", "gemstone", "handmade"],
  },

  // 💄 COSMETICS (3 Products)
  {
    name: "Hydrating Face Serum with Hyaluronic Acid",
    description: "An intensive hydrating serum that plumps and smooths skin, reducing fine lines.",
    brand: "AquaGlow",
    category: "cosmetics",
    price: 1999,
    sku: "COS-SR-018",
    stock: 150,
    availabilityStatus: "In Stock",
    images: ["/images/serum-bottle.jpg"],
    thumbnail: "/images/serum-thumb.jpg",
    specifications: [
      { key: "Volume", value: "30ml" },
      { key: "Skin Type", value: "All" },
    ],
    tags: ["skincare", "face", "hyaluronic"],
  },
  {
    name: "Matte Finish Liquid Lipstick",
    description: "Long-lasting liquid lipstick with a comfortable matte finish. Available in several shades.",
    brand: "ColourPop",
    category: "cosmetics",
    price: 750,
    discountPrice: 650,
    isOnSale: true,
    sku: "COS-LL-019",
    stock: 250,
    availabilityStatus: "In Stock",
    images: ["/images/lipstick-red.jpg"],
    thumbnail: "/images/lipstick-thumb.jpg",
    variants: [{ name: "Shade", value: "Ruby Red, Nude Pink, Berry" }],
    tags: ["makeup", "lips", "matte"],
  },
  {
    name: "Natural Essential Oils Diffuser Set",
    description: "A set of four 100% natural essential oils (Lavender, Peppermint, Eucalyptus, Tea Tree) with a ceramic diffuser.",
    brand: "AromaZen",
    category: "cosmetics",
    price: 2400,
    sku: "COS-EO-020",
    stock: 40,
    availabilityStatus: "In Stock",
    images: ["/images/oils-set.jpg"],
    thumbnail: "/images/oils-thumb.jpg",
    shippingDetails: { weight: 0.8, dimensions: { length: 22, width: 18, height: 10 } },
    tags: ["aromatherapy", "wellness", "home"],
  },
  {
    name: "Cashmere Turtleneck Sweater",
    description: "Ultra-soft and warm 100% cashmere sweater with a ribbed turtleneck design. A luxurious winter staple.",
    brand: "WinterLuxe",
    category: "fashion",
    price: 9500,
    sku: "FAS-SW-005",
    stock: 45,
    availabilityStatus: "In Stock",
    images: ["/images/cashmere-sweater-grey.jpg"],
    thumbnail: "/images/cashmere-sweater-thumb.jpg",
    variants: [
      { name: "Color", value: "Grey, Beige, Black" },
      { name: "Size", value: "S, M, L" },
    ],
    specifications: [
      { key: "Material", value: "100% Cashmere" },
      { key: "Care", value: "Dry Clean Only" },
    ],
    tags: ["sweater", "cashmere", "luxury", "women", "men"],
  },
  {
    name: "Classic Aviator Sunglasses (Polarized)",
    description: "Timeless metal-frame aviator sunglasses with polarized lenses offering 100% UV protection.",
    brand: "SunGuard",
    category: "fashion",
    price: 1850,
    discountPrice: 1570,
    isOnSale: true,
    sku: "FAS-SG-006",
    stock: 120,
    availabilityStatus: "In Stock",
    images: ["/images/aviator-sunglasses.jpg"],
    thumbnail: "/images/aviator-thumb.jpg",
    variants: [{ name: "Lens Color", value: "Black, Brown" }],
    specifications: [{ key: "Protection", value: "UV400 Polarized" }],
    tags: ["accessory", "eyewear", "polarized"],
  },
  {
    name: "High-Waist Yoga Leggings",
    description: "Buttery soft, moisture-wicking leggings perfect for yoga, running, and everyday wear. Features a hidden pocket.",
    brand: "FitFlow",
    category: "fashion",
    price: 2699,
    sku: "FAS-LG-007",
    stock: 95,
    availabilityStatus: "In Stock",
    images: ["/images/yoga-leggings-blue.jpg"],
    thumbnail: "/images/yoga-leggings-thumb.jpg",
    variants: [
      { name: "Color", value: "Navy Blue, Charcoal, Plum" },
      { name: "Size", value: "XS, S, M, L, XL" },
    ],
    tags: ["activewear", "yoga", "leggings", "women"],
  },
  {
    name: "Formal Silk Tie (Striped)",
    description: "Handmade 100% silk tie with a subtle stripe pattern. Perfect for business meetings and formal events.",
    brand: "TieCraft",
    category: "fashion",
    price: 1100,
    sku: "FAS-TI-008",
    stock: 65,
    availabilityStatus: "Limited",
    images: ["/images/striped-tie.jpg"],
    thumbnail: "/images/striped-tie-thumb.jpg",
    specifications: [
      { key: "Material", value: "100% Silk" },
      { key: "Width", value: "7 cm" },
    ],
    tags: ["men", "accessory", "formal"],
  },

  // 📚 BOOKS (3 Products)
  {
    name: "Sapiens: A Brief History of Humankind",
    description: "Yuval Noah Harari's international bestseller exploring the history of Homo sapiens from the Stone Age to the twenty-first century.",
    brand: "Vintage",
    category: "books",
    price: 599,
    discountPrice: 539,
    isOnSale: true,
    sku: "BOK-NHF-008",
    stock: 350,
    availabilityStatus: "In Stock",
    images: ["/images/sapiens-cover.jpg"],
    thumbnail: "/images/sapiens-thumb.jpg",
    specifications: [
      { key: "Format", value: "Paperback" },
      { key: "Genre", value: "Non-Fiction, History" },
    ],
    tags: ["history", "non-fiction", "bestseller"],
  },
  {
    name: "The Lord of the Rings: The Fellowship of the Ring",
    description: "The first volume in J.R.R. Tolkien's epic fantasy trilogy. A journey to destroy the One Ring.",
    brand: "HarperCollins",
    category: "books",
    price: 899,
    sku: "BOK-FAN-009",
    stock: 15,
    availabilityStatus: "Limited",
    images: ["/images/lotr-cover.jpg"],
    thumbnail: "/images/lotr-thumb.jpg",
    specifications: [
      { key: "Format", value: "Hardcover" },
      { key: "Author", value: "J.R.R. Tolkien" },
    ],
    tags: ["fantasy", "classic", "trilogy"],
  },
  {
    name: "Complete Guide to Indian Cooking",
    description: "A comprehensive cookbook with over 500 traditional and modern recipes from various Indian regions.",
    brand: "FoodiePress",
    category: "books",
    price: 1150,
    sku: "BOK-COOK-010",
    stock: 0,
    availabilityStatus: "Out of Stock",
    images: ["/images/indian-cooking-book.jpg"],
    thumbnail: "/images/indian-cooking-thumb.jpg",
    specifications: [
      { key: "Format", value: "Hardcover" },
      { key: "Pages", value: "450" },
    ],
    tags: ["cookbook", "recipes", "cuisine"],
  },

  // 🎶 INSTRUMENT (3 Products)
  {
    name: "Professional Alto Saxophone",
    description: "Intermediate level E-flat alto saxophone with a brass body and mother-of-pearl key buttons. Includes a durable case.",
    brand: "Windsor",
    category: "instrument",
    price: 25000,
    sku: "INS-SAX-011",
    stock: 8,
    availabilityStatus: "Limited",
    images: ["/images/alto-saxophone.jpg"],
    thumbnail: "/images/alto-saxophone-thumb.jpg",
    specifications: [
      { key: "Key", value: "E-flat" },
      { key: "Finish", value: "Lacquered Brass" },
    ],
    shippingDetails: { weight: 5.5, dimensions: { length: 65, width: 30, height: 20 } },
    tags: ["brass", "wind", "saxophone", "professional"],
  },
  {
    name: "Ukulele Starter Pack (Concert)",
    description: "Concert size ukulele made from mahogany wood. Comes with a tuner, gig bag, and instructional booklet.",
    brand: "AlohaTunes",
    category: "instrument",
    price: 3200,
    discountPrice: 2880,
    isOnSale: true,
    sku: "INS-UK-012",
    stock: 80,
    availabilityStatus: "In Stock",
    images: ["/images/ukulele-pack.jpg"],
    thumbnail: "/images/ukulele-thumb.jpg",
    specifications: [
      { key: "Size", value: "Concert" },
      { key: "Material", value: "Mahogany" },
    ],
    tags: ["string", "ukulele", "starter"],
  },
  {
    name: "Electronic Drum Kit (Mesh Heads)",
    description: "Full electronic drum kit featuring realistic mesh heads for quiet practice and authentic feel. Includes a module with 20 preset kits.",
    brand: "RhythmTech",
    category: "instrument",
    price: 45000,
    sku: "INS-DRM-013",
    stock: 5,
    availabilityStatus: "Limited",
    images: ["/images/electronic-drums.jpg"],
    thumbnail: "/images/electronic-drums-thumb.jpg",
    shippingDetails: { weight: 30.0, dimensions: { length: 120, width: 80, height: 60 } },
    tags: ["percussion", "electronic", "drums"],
  },

  // 📱 GADGETS (4 Products)
  {
    name: "4K Portable Projector",
    description: "Compact, high-brightness 4K projector for home cinema or business presentations. Supports screen mirroring.",
    brand: "ViewMaster",
    category: "gadgets",
    price: 28000,
    sku: "GAD-PR-015",
    stock: 35,
    availabilityStatus: "In Stock",
    images: ["/images/4k-projector.jpg"],
    thumbnail: "/images/4k-projector-thumb.jpg",
    specifications: [
      { key: "Resolution", value: "4K Supported" },
      { key: "Brightness", value: "2000 Lumens" },
    ],
    tags: ["home-cinema", "projector", "electronics"],
  },
  {
    name: "Universal Travel Adapter with USB Ports",
    description: "All-in-one travel adapter covering US, EU, UK, and AUS plugs. Features 2 USB-A and 1 USB-C fast-charging ports.",
    brand: "GlobeTrek",
    category: "gadgets",
    price: 1599,
    discountPrice: 1350,
    isOnSale: true,
    sku: "GAD-TA-016",
    stock: 200,
    availabilityStatus: "In Stock",
    images: ["/images/travel-adapter.jpg"],
    thumbnail: "/images/travel-adapter-thumb.jpg",
    specifications: [
      { key: "Ports", value: "3 (2x USB-A, 1x USB-C)" },
      { key: "Safety", value: "Built-in Fuse" },
    ],
    tags: ["travel", "adapter", "charging"],
  },
  {
    name: "Mechanical Gaming Keyboard",
    description: "Full-size mechanical keyboard with tactile brown switches, customizable RGB backlighting, and a durable metal frame.",
    brand: "GameForge",
    category: "gadgets",
    price: 6200,
    sku: "GAD-KB-017",
    stock: 50,
    availabilityStatus: "In Stock",
    images: ["/images/gaming-keyboard.jpg"],
    thumbnail: "/images/gaming-keyboard-thumb.jpg",
    variants: [{ name: "Switch Type", value: "Brown, Red" }],
    specifications: [
      { key: "Switches", value: "Tactile Mechanical" },
      { key: "Layout", value: "Full 104-Key" },
    ],
    tags: ["gaming", "peripherals", "keyboard"],
  },
  {
    name: "Voice-Activated Smart Speaker",
    description: "A compact smart speaker with far-field voice recognition, premium sound, and smart home control capabilities.",
    brand: "HomeAI",
    category: "gadgets",
    price: 4499,
    sku: "GAD-SS-018",
    stock: 0,
    availabilityStatus: "Out of Stock",
    images: ["/images/smart-speaker.jpg"],
    thumbnail: "/images/smart-speaker-thumb.jpg",
    variants: [{ name: "Color", value: "Chalk, Charcoal" }],
    tags: ["smart-home", "audio", "voice-assistant"],
  },

  // 💎 JEWELERY (3 Products)
  {
    name: "Rose Gold Heart Pendant Necklace",
    description: "Delicate heart-shaped pendant plated in 18k rose gold, featuring tiny inlaid crystals. 45cm chain.",
    brand: "Lovelace",
    category: "jewelery",
    price: 3800,
    sku: "JWL-PN-018",
    stock: 55,
    availabilityStatus: "In Stock",
    images: ["/images/rose-gold-pendant.jpg"],
    thumbnail: "/images/rose-gold-pendant-thumb.jpg",
    specifications: [
      { key: "Metal", value: "18K Rose Gold Plated" },
      { key: "Chain Length", value: "45 cm" },
    ],
    tags: ["necklace", "pendant", "rose-gold", "women"],
  },
  {
    name: "Custom Engravable Cufflinks",
    description: "Polished rectangular stainless steel cufflinks, ideal for formal wear. Can be custom engraved.",
    brand: "GentleMan",
    category: "jewelery",
    price: 2100,
    discountPrice: 1890,
    isOnSale: true,
    sku: "JWL-CL-019",
    stock: 70,
    availabilityStatus: "In Stock",
    images: ["/images/steel-cufflinks.jpg"],
    thumbnail: "/images/steel-cufflinks-thumb.jpg",
    specifications: [{ key: "Material", value: "Stainless Steel" }],
    tags: ["men", "accessory", "cufflinks", "formal"],
  },
  {
    name: "Bohemian Turquoise Bangle",
    description: "Wide, oxidised silver-plated bangle inlaid with natural turquoise stones. A bold, statement piece.",
    brand: "GypsySoul",
    category: "jewelery",
    price: 4999,
    sku: "JWL-BG-020",
    stock: 18,
    availabilityStatus: "Limited",
    images: ["/images/turquoise-bangle.jpg"],
    thumbnail: "/images/turquoise-bangle-thumb.jpg",
    variants: [{ name: "Size", value: "Adjustable" }],
    tags: ["bangle", "turquoise", "bohemian", "statement"],
  },

  // 💄 COSMETICS (3 Products)
  {
    name: "All-Natural Clay Face Mask",
    description: "Detoxifying and purifying clay mask with activated charcoal and tea tree oil to clear pores and brighten skin.",
    brand: "PureEarth",
    category: "cosmetics",
    price: 899,
    sku: "COS-FM-021",
    stock: 130,
    availabilityStatus: "In Stock",
    images: ["/images/clay-mask-jar.jpg"],
    thumbnail: "/images/clay-mask-thumb.jpg",
    specifications: [
      { key: "Volume", value: "100g" },
      { key: "Ingredients", value: "Natural Clay, Charcoal" },
    ],
    tags: ["skincare", "mask", "detox"],
  },
  {
    name: "Professional Makeup Brush Set (12 Pcs)",
    description: "A complete set of 12 vegan and cruelty-free makeup brushes for face and eyes, with soft synthetic bristles.",
    brand: "BrushPro",
    category: "cosmetics",
    price: 1650,
    discountPrice: 1400,
    isOnSale: true,
    sku: "COS-BS-022",
    stock: 90,
    availabilityStatus: "In Stock",
    images: ["/images/brush-set.jpg"],
    thumbnail: "/images/brush-set-thumb.jpg",
    specifications: [{ key: "Bristle Type", value: "Synthetic (Vegan)" }],
    tags: ["makeup", "tools", "brush"],
  },
  {
    name: "Organic Beard Oil",
    description: "A blend of argan, jojoba, and cedarwood oils to soften, condition, and nourish the beard and skin underneath.",
    brand: "BeardCo",
    category: "cosmetics",
    price: 650,
    sku: "COS-BO-023",
    stock: 60,
    availabilityStatus: "In Stock",
    images: ["/images/beard-oil.jpg"],
    thumbnail: "/images/beard-oil-thumb.jpg",
    specifications: [
      { key: "Volume", value: "50ml" },
      { key: "Scent", value: "Cedarwood" },
    ],
    tags: ["men", "grooming", "beard"],
  },
];

export default products;